FROM ubuntu:16.04

ADD requirements.txt .
ADD main.py .

RUN apt-get update \
    && apt-get install -y python3-pip python-psycopg2 libpq-dev \
    && pip3 install --upgrade pip setuptools\
    && pip3 install --no-cache-dir -r requirements.txt \
    && rm -rf /tmp/* \
    && apt-get clean \
    && apt-get remove -y python3-pip python python2.7 python2.7-minimal \
    && apt-mark manual python3 \
    && apt-get autoremove -y \
    && chmod +x  main.py

CMD ["python3","-u","main.py"]
